
raw:
    n100: raw/n100
    cams: raw/cams

data:
    n100: data/n100
    cams: data/cams
    final: data/final

load_data:
    n100: False
    cams: False

preprocess:
    n100: False
    cams: False
    unite: False

cities: data/city_locations.csv

fit_model: False
