name: inar
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.1
  - bleach=3.1.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - certifi=2018.8.24
  - cffi=1.11.5
  - cfgrib=0.9.7.7
  - click=7.0
  - curl=7.63.0
  - cycler=0.10.0
  - dbus=1.13.12
  - decorator=4.4.1
  - defusedxml=0.6.0
  - eccodes=2.12.3
  - ecmwf-api-client=1.4
  - entrypoints=0.2.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icu=58.2
  - ipykernel=4.10.0
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - jasper=1.900.1
  - jedi=0.12.1
  - jinja2=2.11.1
  - jpeg=9c
  - json5=0.9.1
  - jsonschema=2.6.0
  - jupyter_client=5.3.3
  - jupyter_core=4.5.0
  - jupyterlab=1.2.6
  - jupyterlab_server=1.0.0
  - kiwisolver=1.0.1
  - krb5=1.16.2
  - libaec=1.0.4
  - libcurl=7.63.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libnetcdf=4.6.2
  - libpng=1.6.37
  - libsodium=1.0.16
  - libssh2=1.8.0
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.0
  - matplotlib=3.0.0
  - mistune=0.8.3
  - nbconvert=5.5.0
  - nbformat=5.0.4
  - ncurses=6.1
  - notebook=5.6.0
  - numpy=1.14.6
  - openblas=0.2.20
  - openssl=1.0.2u
  - pandas=0.22.0
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.1
  - pcre=8.43
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pip=10.0.1
  - prometheus_client=0.7.1
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.5.2
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - python=3.5.6
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyyaml=3.13
  - pyzmq=17.1.2
  - qt=5.9.6
  - readline=7.0
  - send2trash=1.5.0
  - setuptools=40.2.0
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.11.0
  - sqlite=3.31.1
  - terminado=0.8.1
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=5.1.1
  - traitlets=4.3.2
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.31.1
  - xarray=0.13.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zlib=1.2.11

